# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cicd-project-management

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: ${{ vars.DATABASE_URL}}
  PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK: ${{ vars.PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK}}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 6: Run tests
      - name: Run npm test
        run: |
          npx playwright install
          npx playwright test --config=configs/playwright.config.js

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_216D47E391DC49DA99613619C21C1B53 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F67BF1FD0A7F40028B5DB637A2CE7313 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4CCA32DEDA7343D2BDA41388BCE5E5E5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cicd-project-management'
          slot-name: 'Production'
          package: .
          
